//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshelf.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookshelf.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string AddBookAcceptButton {
            get {
                return ResourceManager.GetString("AddBookAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string AddBookAuthorTextBlock {
            get {
                return ResourceManager.GetString("AddBookAuthorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string AddBookCancelButton {
            get {
                return ResourceManager.GetString("AddBookCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая книга.
        /// </summary>
        public static string AddBookHeaderTextBlock {
            get {
                return ResourceManager.GetString("AddBookHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полка.
        /// </summary>
        public static string AddBookShelfTextBlock {
            get {
                return ResourceManager.GetString("AddBookShelfTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string AddBookTitleTextBlock {
            get {
                return ResourceManager.GetString("AddBookTitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string AddShelfAcceptButton {
            get {
                return ResourceManager.GetString("AddShelfAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая полка.
        /// </summary>
        public static string AddShelfHeaderTextBlock {
            get {
                return ResourceManager.GetString("AddShelfHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        public static string AddShelfTitleTextBlock {
            get {
                return ResourceManager.GetString("AddShelfTitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string BookCancelButton {
            get {
                return ResourceManager.GetString("BookCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string BookEditButton {
            get {
                return ResourceManager.GetString("BookEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string BookSaveButton {
            get {
                return ResourceManager.GetString("BookSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        public static string BookViewISBNTextBlock {
            get {
                return ResourceManager.GetString("BookViewISBNTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество страниц:.
        /// </summary>
        public static string BookViewNumberOfPagesTextBlock {
            get {
                return ResourceManager.GetString("BookViewNumberOfPagesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочитано страниц:.
        /// </summary>
        public static string BookViewPagesReadTextBlock {
            get {
                return ResourceManager.GetString("BookViewPagesReadTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издательство:.
        /// </summary>
        public static string BookViewPublisherTextBlock {
            get {
                return ResourceManager.GetString("BookViewPublisherTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        public static string BookViewStatusTextBlock {
            get {
                return ResourceManager.GetString("BookViewStatusTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год публикации:.
        /// </summary>
        public static string BookViewYearTextBlock {
            get {
                return ResourceManager.GetString("BookViewYearTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string EditBookAcceptButton {
            get {
                return ResourceManager.GetString("EditBookAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string EditBookCancelButton {
            get {
                return ResourceManager.GetString("EditBookCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование книги.
        /// </summary>
        public static string EditBookHeaderTextBlock {
            get {
                return ResourceManager.GetString("EditBookHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Добавить новую книгу.
        /// </summary>
        public static string ShelfAddNewBookButton {
            get {
                return ResourceManager.GetString("ShelfAddNewBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ShelfBackButton {
            get {
                return ResourceManager.GetString("ShelfBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полки.
        /// </summary>
        public static string ShelfNameTextBlock {
            get {
                return ResourceManager.GetString("ShelfNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +  Добавить полку.
        /// </summary>
        public static string ShelvesAddNewShelfButton {
            get {
                return ResourceManager.GetString("ShelvesAddNewShelfButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ShelvesBackButton {
            get {
                return ResourceManager.GetString("ShelvesBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string SideBarHomeButton {
            get {
                return ResourceManager.GetString("SideBarHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        public static string SideBarNoteButton {
            get {
                return ResourceManager.GetString("SideBarNoteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полки.
        /// </summary>
        public static string SideBarShelvesButton {
            get {
                return ResourceManager.GetString("SideBarShelvesButton", resourceCulture);
            }
        }
    }
}
